### ISSUE TITLE
Document how to create settings.json

### ISSUE THREAD

**Issue by ArcadeCityMayor** [Cameri/nostr-ts-relay#2]
The setup instructions don't mention the `~/.nostr/settings.json` the app is looking for.

The caught error in `createSettings` returns default settings, but `saveSettingsOnExit` fails to do anything if it can't find the original settings file.

Unclear if the relay is working as expected without a settings.json file. How do we create one?

**Comment by Cameri** [comment]
I'll look into it. The relay works fine with the default settings if it can't create settings file.

**Comment by ArcadeCityMayor** [comment]
And minor nit: My local postgres complained about the hyphens in nostr-ts-relay for DB name

**Comment by Cameri** [comment]
@ArcadeCityMayor Should have been fixed in https://github.com/Cameri/nostr-ts-relay/pull/1

**Comment by Cameri** [comment]
Closing since this issue has been resolved. If not, please re-open.
